'use client';

import Link from "next/link";

export default function TermsAndConditions() {
  return (
    <div className="wrapper">
      <div className="breadcrumb-block">
        <div className="container">
          <div className="row">
            <div className="col-lg-12 col-md-10">
              <div className="barren-breadcrumb">
                <nav aria-label="breadcrumb">
                  <ol className="breadcrumb">
                    <li className="breadcrumb-item">
                      <Link href="/">Home</Link>
                    </li>
                    <li className="breadcrumb-item active" aria-current="page">
                      Terms & Conditions
                    </li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="event-dt-block p-80">
        <div className="container">
          <div className="row">
            <div className="col-lg-12 col-md-12">
              <div className="main-title">
                <h3>Terms & Conditions</h3>
              </div>
              <div className="policy-content main-form">
                <h4>Introduction</h4>
                <p>
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://bukitnow.org">bukitnow.org</a>, including the related mobile site and mobile application (hereinafter 3 referred to as “Platform”). The Platform is owned by a company incorporated under the Companies Act, 1956 with its registered office at (hereinafter referred to as &quot;Platform Owner&quot;, “we”, “us”, “our”). Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use Bukit,
relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, “Services”). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates. For the purpose of these Terms of Use, wherever the context so requires &quot;you&quot;, “your” or &quot;user&quot; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. The use of Platform and/or availing of our Services is subject to the following Terms of Use: To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform. Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements. The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics. You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws. You agree to pay us the charges associated with availing the Services. You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or 4 forbidden by these Terms, or Indian or local laws that might apply to you. You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information. You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services. You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party. In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages,
including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services, however caused and whether arising in contract, tort, negligence, warranty or otherwise, exceed the amount paid by You for using the Services giving rise to the cause of action or Rupees One Hundred (Rs. 100) whichever is less Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event. These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India. All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
                </p>

                {/* <h4>Platform Usage</h4>
                <p>
                  Your use of the Platform and services and tools are governed by these terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. By using the Platform, you agree to be bound by these Terms of Use.
                </p>

                <h4>User Obligations</h4>
                <ul>
                  <li>Provide accurate and complete information during registration</li>
                  <li>Be responsible for all actions through your account</li>
                  <li>Use the platform for lawful purposes only</li>
                  <li>Pay all applicable charges for services</li>
                  <li>Not misuse or attempt to hack the platform</li>
                </ul> */}

                {/* <h4>Shipping Policy</h4>
                <p>
                  <strong>Processing Time:</strong> All orders are delivered within 2-3 business days. Orders are not shipped or delivered on weekends or holidays. If we are experiencing a high volume of orders, shipments may be delayed by a few days. Please allow additional days in transit for delivery. If there will be a significant delay in the shipment of your order, we will contact you via email or phone. 
                </p>
                <p>
                  <strong>Domestic Shipping:</strong> Orders will be delivered within 3 to 4 weeks from the date of order confirmation. Please note that delivery times may be affected by factors beyond our control, such as weather conditions, customs delays, and other unforeseen circumstances.
                </p> */}

                <h4>Return & Refund Policy</h4>
                <p>
                  <strong>Returns:</strong> We have a 5-day return policy from the date of receiving your item. Once the return product is received it will be inspected and the return will be approved within 2 days
                </p>
                <p>
                  <strong>Refunds:</strong> Approved refunds will be processed within 10 business days to your original payment method. If approved, you’ll be automatically refunded on your original payment method within 10 business days. Please remember it can take some time for your bank or credit card company to process and post the refund too. If more than 15 business days have passed since we’ve approved your return, please contact us
                </p>

                {/* <h4>Intellectual Property</h4>
                <p>
                  The contents of the Platform are proprietary and you will not have any authority to claim any intellectual property rights, title, or interest in its contents.
                </p>

                <h4>Limitation of Liability</h4>
                <p>
                  In no event will we be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues.
                </p> */}

                {/* <h4>Governing Law</h4>
                <p>
                  These Terms and any dispute or claim relating to it shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in India.
                </p> */}

                <div className="contact-details mt-4">
                  <p>For any queries regarding these terms, please contact us at:</p>
                  <p>Email: support.Bukit@gmail.com</p>
                  <p>Phone: +91 96558 95914</p>
                </div>

                <div className="policy-last-updated">
                  <p>Last Updated: 21/12/2024</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
} 